// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPFMndL5z9dwqcM97k5s7PY2BNIsJbocA',
    appId: '1:885018943861:web:6c410699650b309bbbf33c',
    messagingSenderId: '885018943861',
    projectId: 'poker-night-tools',
    authDomain: 'poker-night-tools.firebaseapp.com',
    storageBucket: 'poker-night-tools.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz1oVEyLxbKLhRGo4-k1QCfX02lKtyzEU',
    appId: '1:885018943861:android:8120a34ba8cc08f5bbf33c',
    messagingSenderId: '885018943861',
    projectId: 'poker-night-tools',
    storageBucket: 'poker-night-tools.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNUgUjpSJm941UCC5tC3D6bo2hiivi6hU',
    appId: '1:885018943861:ios:8460e140cad8f9f8bbf33c',
    messagingSenderId: '885018943861',
    projectId: 'poker-night-tools',
    storageBucket: 'poker-night-tools.firebasestorage.app',
    iosBundleId: 'com.pokernight.pokerNight',
  );
}
