import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';

import '../../app/colors.dart';
import '../../app/route_paths.dart';
import '../../app/typography.dart';
import '../../constants/app_constants.dart';
import '../../models/chip_color.dart';
import '../../models/tournament_preset.dart';
import '../../providers/app_provider.dart';
import '../../utils/mock_data.dart';
import '../../utils/tournament_engine.dart';
import '../../widgets/app_button.dart';
import '../../widgets/app_card.dart';
import '../../widgets/app_empty_state.dart';
import '../../widgets/app_modal.dart';
import '../../widgets/app_page.dart';
import '../../widgets/app_select.dart';
import '../../widgets/app_text_field.dart';
import '../../widgets/app_toggle.dart';
import '../../widgets/chip_token.dart';

/// Tournament preset manager (checklist §9.1): create, edit, delete and use
/// saved tournament templates. Presets store inputs only — the blind structure
/// is always regenerated by the engine (09-003).
class PresetsScreen extends StatefulWidget {
  const PresetsScreen({super.key});

  @override
  State<PresetsScreen> createState() => _PresetsScreenState();
}

class _PresetsScreenState extends State<PresetsScreen> {
  void _editPreset(AppProvider app, TournamentPreset? preset) {
    showAppModal(
      context: context,
      title: preset == null ? 'New preset' : 'Edit preset',
      maxWidth: 560,
      child: _PresetForm(
        preset: preset,
        chipSetNames: _chipSetNames(app),
        onSave: (data) {
          final p = _buildPreset(app, preset, data);
          app.savePreset(p);
          Navigator.of(context).pop();
        },
      ),
    );
  }

  List<String> _chipSetNames(AppProvider app) => [
        ...TournamentEngine.presetNames,
        for (final cs in app.savedChipSets) cs.name,
      ];

  TournamentPreset _buildPreset(
    AppProvider app,
    TournamentPreset? existing,
    _PresetDraft data,
  ) {
    return TournamentPreset(
      id: existing?.id ?? 'pr-${DateTime.now().millisecondsSinceEpoch}',
      name: data.name,
      buyIn: data.buyIn,
      koEnabled: data.koEnabled,
      koAmount: data.koAmount,
      rebuys: data.rebuys,
      rebuysCloseLevel: data.rebuysCloseLevel,
      reEntry: data.reEntry,
      addOn: data.addOn,
      durationHours: data.durationHours,
      anteEnabled: data.anteEnabled,
      anteAfterLevel: data.anteAfterLevel,
      organizerPct: data.organizerPct,
      chipSetName: data.chipSetName,
      chipSet: _chipsFor(app, data.chipSetName),
    );
  }

  List<ChipColor> _chipsFor(AppProvider app, String name) {
    if (TournamentEngine.presetNames.contains(name)) {
      return List.of(TournamentEngine.getPreset(name));
    }
    for (final cs in app.savedChipSets) {
      if (cs.name == name) return List.of(cs.chips);
    }
    return List.of(MockData.defaultChipSet);
  }

  Future<void> _confirmDelete(TournamentPreset preset, AppProvider app) async {
    final ok = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppColors.card,
        title: const Text('Delete preset?'),
        content: Text(
          '"${preset.name}" will be removed. Games already created from it are not affected.',
          style: AppTypography.bodySm,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: Text('Cancel', style: AppTypography.bodySm.copyWith(color: AppColors.mutedForeground)),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(true),
            child: Text(
              'Delete',
              style: AppTypography.bodySm.copyWith(color: AppColors.destructive),
            ),
          ),
        ],
      ),
    );
    if (ok == true) app.deletePreset(preset.id);
  }

  @override
  Widget build(BuildContext context) {
    final app = context.watch<AppProvider>();
    final presets = app.presets;

    return AppPage(
      maxWidth: 760,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Tournament Presets',
                      style: AppTypography.display(size: AppFontSizes.xxl, weight: FontWeight.w700),
                    ),
                    const SizedBox(height: AppSpacing.xs),
                    Text(
                      'Save your favourite game settings and start a new tournament in one tap.',
                      style: AppTypography.bodySm.copyWith(color: AppColors.mutedForeground),
                    ),
                  ],
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 4.0),
                child: AppButton(
                  onPressed: () => _editPreset(app, null),
                  child: const Text('+ New preset'),
                ),
              ),
            ],
          ),
          const SizedBox(height: AppSpacing.lg),
          if (presets.isEmpty)
            const AppEmptyState(
              icon: Icons.list_alt_outlined,
              title: 'No presets yet',
              description: 'Save a tournament configuration to reuse it later.',
            )
          else
            Column(
              children: [
                for (final p in presets)
                  AppCard(
                    padding: const EdgeInsets.all(AppSpacing.lg),
                    margin: const EdgeInsets.only(bottom: AppSpacing.md),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Expanded(
                              child: Text(
                                p.name,
                                style: AppTypography.bodyLg.copyWith(fontWeight: FontWeight.w600),
                              ),
                            ),
                            IconButton(
                              visualDensity: VisualDensity.compact,
                              tooltip: 'Edit',
                              onPressed: () => _editPreset(app, p),
                              icon: const Icon(Icons.edit_outlined, size: 18, color: AppColors.mutedForeground),
                            ),
                            IconButton(
                              visualDensity: VisualDensity.compact,
                              tooltip: 'Delete',
                              onPressed: () => _confirmDelete(p, app),
                              icon: const Icon(Icons.delete_outline, size: 18, color: AppColors.mutedForeground),
                            ),
                          ],
                        ),
                        const SizedBox(height: AppSpacing.xs),
                        Wrap(
                          spacing: AppSpacing.sm,
                          runSpacing: AppSpacing.xs,
                          children: [
                            _Tag(text: 'Buy-in ${p.buyIn}'),
                            _Tag(text: '${_hours(p.durationHours)}h'),
                            _Tag(text: p.rebuys ? 'Rebuys to L${p.rebuysCloseLevel}' : 'No rebuys'),
                            _Tag(text: p.addOn ? 'Add-on' : 'No add-on'),
                            _Tag(text: p.koEnabled ? 'KO ${p.koAmount}' : 'No KO'),
                            _Tag(text: p.anteEnabled ? 'Ante L${p.anteAfterLevel}+' : 'No ante'),
                            _Tag(text: '${p.organizerPct}% org'),
                            _Tag(text: p.chipSetName),
                          ],
                        ),
                        const SizedBox(height: AppSpacing.sm),
                        Wrap(
                          spacing: AppSpacing.xs,
                          runSpacing: AppSpacing.xs,
                          children: [
                            for (final c in p.chipSet)
                              ChipToken(
                                colorName: c.color,
                                hex: c.colorValue,
                                value: c.value,
                                count: c.quantity,
                              ),
                          ],
                        ),
                        const SizedBox(height: AppSpacing.md),
                        Align(
                          alignment: Alignment.centerLeft,
                          child: AppButton(
                            size: AppButtonSize.sm,
                            onPressed: () => context.go(
                              '${RoutePaths.createTournament}?preset=${p.id}',
                            ),
                            child: const Text('Use for new game'),
                          ),
                        ),
                      ],
                    ),
                  ),
              ],
            ),
        ],
      ),
    );
  }

  static String _hours(double h) =>
      h == h.roundToDouble() ? '${h.round()}' : '$h';
}

class _Tag extends StatelessWidget {
  const _Tag({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: AppSpacing.sm, vertical: 3),
      decoration: BoxDecoration(
        color: AppColors.secondary,
        borderRadius: BorderRadius.circular(AppRadius.pill),
        border: Border.all(color: AppColors.border),
      ),
      child: Text(text, style: AppTypography.bodyXs.copyWith(color: AppColors.mutedForeground)),
    );
  }
}

class _PresetDraft {
  _PresetDraft({
    required this.name,
    required this.buyIn,
    required this.koEnabled,
    required this.koAmount,
    required this.rebuys,
    required this.rebuysCloseLevel,
    required this.reEntry,
    required this.addOn,
    required this.durationHours,
    required this.anteEnabled,
    required this.anteAfterLevel,
    required this.organizerPct,
    required this.chipSetName,
  });

  final String name;
  final int buyIn;
  final bool koEnabled;
  final int koAmount;
  final bool rebuys;
  final int rebuysCloseLevel;
  final bool reEntry;
  final bool addOn;
  final double durationHours;
  final bool anteEnabled;
  final int anteAfterLevel;
  final int organizerPct;
  final String chipSetName;
}

class _PresetForm extends StatefulWidget {
  const _PresetForm({
    required this.preset,
    required this.chipSetNames,
    required this.onSave,
  });

  final TournamentPreset? preset;
  final List<String> chipSetNames;
  final ValueChanged<_PresetDraft> onSave;

  @override
  State<_PresetForm> createState() => _PresetFormState();
}

class _PresetFormState extends State<_PresetForm> {
  late final TextEditingController _name;
  late final TextEditingController _buyIn;
  late final TextEditingController _koAmount;
  late bool _koEnabled;
  late bool _rebuys;
  late int _rebuysCloseLevel;
  late bool _reEntry;
  late bool _addOn;
  late double _duration;
  late bool _anteEnabled;
  late int _anteAfterLevel;
  late double _orgPct;
  late String _chipSetName;
  String? _error;

  @override
  void initState() {
    super.initState();
    final p = widget.preset;
    _name = TextEditingController(text: p?.name ?? '');
    _buyIn = TextEditingController(text: p?.buyIn.toString() ?? '15');
    _koAmount = TextEditingController(text: p?.koAmount.toString() ?? '5');
    _koEnabled = p?.koEnabled ?? false;
    _rebuys = p?.rebuys ?? true;
    _rebuysCloseLevel = p?.rebuysCloseLevel ?? 6;
    _reEntry = p?.reEntry ?? true;
    _addOn = p?.addOn ?? true;
    _duration = p?.durationHours ?? 3.5;
    _anteEnabled = p?.anteEnabled ?? true;
    _anteAfterLevel = p?.anteAfterLevel ?? 6;
    _orgPct = (p?.organizerPct ?? 10).toDouble();
    _chipSetName = p?.chipSetName ??
        (widget.chipSetNames.isNotEmpty ? widget.chipSetNames.first : 'Standard 300');
  }

  @override
  void dispose() {
    _name.dispose();
    _buyIn.dispose();
    _koAmount.dispose();
    super.dispose();
  }

  void _submit() {
    final name = _name.text.trim();
    final buyIn = num.tryParse(_buyIn.text.trim());
    final ko = num.tryParse(_koAmount.text.trim());
    if (name.length < 2) {
      setState(() => _error = 'Preset name must be at least 2 characters.');
      return;
    }
    if (buyIn == null || buyIn <= 0) {
      setState(() => _error = 'Buy-in must be a positive number.');
      return;
    }
    if (ko == null || ko <= 0) {
      setState(() => _error = 'KO bounty must be a positive number.');
      return;
    }
    widget.onSave(_PresetDraft(
      name: name,
      buyIn: buyIn.toInt(),
      koEnabled: _koEnabled,
      koAmount: ko.toInt(),
      rebuys: _rebuys,
      rebuysCloseLevel: _rebuysCloseLevel,
      reEntry: _reEntry,
      addOn: _addOn,
      durationHours: _duration,
      anteEnabled: _anteEnabled,
      anteAfterLevel: _anteAfterLevel,
      organizerPct: _orgPct.round(),
      chipSetName: _chipSetName,
    ));
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        AppTextField(
          controller: _name,
          label: 'Preset name',
          placeholder: 'e.g. Friday Night Regular',
        ),
        const SizedBox(height: AppSpacing.lg),
        Row(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            Expanded(
              child: AppTextField(
                controller: _buyIn,
                label: 'Buy-in',
                keyboardType: TextInputType.number,
              ),
            ),
            const SizedBox(width: AppSpacing.md),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Target duration', style: AppTypography.bodySm.copyWith(color: AppColors.mutedForeground)),
                  const SizedBox(height: AppSpacing.xs),
                  DropdownButtonFormField<String>(
                    initialValue: _duration.toString(),
                    isExpanded: true,
                    dropdownColor: AppColors.card,
                    style: AppTypography.bodyStyle,
                    decoration: InputDecoration(
                      isDense: true,
                      filled: true,
                      fillColor: AppColors.card,
                      contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 11),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(AppRadius.sm),
                        borderSide: const BorderSide(color: AppColors.border),
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(AppRadius.sm),
                        borderSide: const BorderSide(color: AppColors.ring),
                      ),
                    ),
                    items: [
                      for (final d in [3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0])
                        DropdownMenuItem(
                          value: d.toString(),
                          child: Text('${d == d.roundToDouble() ? d.round() : d}h'),
                        ),
                    ],
                    onChanged: (v) => setState(() => _duration = double.tryParse(v ?? '') ?? 3.5),
                  ),
                ],
              ),
            ),
          ],
        ),
        const SizedBox(height: AppSpacing.lg),
        _FieldToggle(
          title: 'KO bounty',
          subtitle: 'Side payment for eliminating a player',
          value: _koEnabled,
          onChanged: (v) => setState(() => _koEnabled = v),
        ),
        if (_koEnabled) ...[
          const SizedBox(height: AppSpacing.sm),
          SizedBox(
            width: 120,
            child: AppTextField(
              controller: _koAmount,
              label: 'Bounty amount',
              keyboardType: TextInputType.number,
            ),
          ),
        ],
        const Divider(color: AppColors.border),
        _FieldToggle(
          title: 'Rebuys',
          subtitle: 'Players can re-enter after elimination',
          value: _rebuys,
          onChanged: (v) => setState(() => _rebuys = v),
        ),
        if (_rebuys) ...[
          const SizedBox(height: AppSpacing.sm),
          AppSelect(
            label: 'Close rebuys',
            value: '$_rebuysCloseLevel',
            onChanged: (v) => setState(() => _rebuysCloseLevel = int.tryParse(v ?? '') ?? 6),
            items: [
              for (var n = 4; n <= 8; n++)
                DropdownMenuItem(value: '$n', child: Text('End of Level $n')),
            ],
          ),
        ],
        const Divider(color: AppColors.border),
        _FieldToggle(
          title: 'Re-entry',
          subtitle: 'Buy a new entry stack after elimination',
          value: _reEntry,
          onChanged: (v) => setState(() => _reEntry = v),
        ),
        const Divider(color: AppColors.border),
        _FieldToggle(
          title: 'Add-on',
          subtitle: 'One per active player at rebuy close',
          value: _addOn,
          onChanged: (v) => setState(() => _addOn = v),
        ),
        const Divider(color: AppColors.border),
        _FieldToggle(
          title: 'Ante',
          subtitle: 'Big blind ante',
          value: _anteEnabled,
          onChanged: (v) => setState(() => _anteEnabled = v),
        ),
        if (_anteEnabled) ...[
          const SizedBox(height: AppSpacing.sm),
          AppSelect(
            label: 'Activate ante',
            value: '$_anteAfterLevel',
            onChanged: (v) => setState(() => _anteAfterLevel = int.tryParse(v ?? '') ?? 6),
            items: [
              for (var n = 4; n <= 8; n++)
                DropdownMenuItem(value: '$n', child: Text('After Level $n')),
            ],
          ),
        ],
        const Divider(color: AppColors.border),
        AppSelect(
          label: 'Chip set',
          value: _chipSetName,
          onChanged: (v) {
            if (v != null) setState(() => _chipSetName = v);
          },
          items: [
            for (final name in widget.chipSetNames)
              DropdownMenuItem(value: name, child: Text(name)),
          ],
        ),
        const SizedBox(height: AppSpacing.lg),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Organiser percentage', style: AppTypography.bodySm.copyWith(fontWeight: FontWeight.w500)),
            Row(
              children: [
                Expanded(
                  child: Slider(
                    value: _orgPct,
                    min: 0,
                    max: 20,
                    divisions: 20,
                    activeColor: AppColors.primary,
                    inactiveColor: AppColors.border,
                    onChanged: (v) => setState(() => _orgPct = v),
                  ),
                ),
                const SizedBox(width: AppSpacing.md),
                SizedBox(
                  width: 44,
                  child: Text(
                    '${_orgPct.round()}%',
                    textAlign: TextAlign.right,
                    style: AppTypography.mono(size: AppFontSizes.sm, color: AppColors.primary),
                  ),
                ),
              ],
            ),
          ],
        ),
        if (_error != null) ...[
          const SizedBox(height: AppSpacing.sm),
          Text(_error!, style: AppTypography.bodyXs.copyWith(color: AppColors.destructive)),
        ],
        const SizedBox(height: AppSpacing.lg),
        AppButton(
          fullWidth: true,
          onPressed: _submit,
          child: const Text('Save preset'),
        ),
      ],
    );
  }
}

class _FieldToggle extends StatelessWidget {
  const _FieldToggle({
    required this.title,
    required this.subtitle,
    required this.value,
    required this.onChanged,
  });

  final String title;
  final String subtitle;
  final bool value;
  final ValueChanged<bool> onChanged;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: AppSpacing.sm),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: AppTypography.bodySm.copyWith(fontWeight: FontWeight.w500)),
                const SizedBox(height: 2),
                Text(subtitle, style: AppTypography.bodyXs.copyWith(color: AppColors.mutedForeground)),
              ],
            ),
          ),
          AppToggle(value: value, onChanged: onChanged),
        ],
      ),
    );
  }
}
